# Generated by Django 4.1.1 on 2022-10-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='almoco',
            name='refeicao',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='janta',
            name='refeicao',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manha',
            name='refeicao',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
